<a href="https://colab.research.google.com/github/BitnooriLee/Into-Data-Science-and-AI/blob/main/Assignment5_2022_Bitnoori_Lee.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

$\qquad$ $\qquad$$\qquad$  **DAT405 Introduction to Data Science and AI, LP4 2022** <br />
$\qquad$ $\qquad$$\qquad$                   **Assignment 5: Reinforcement learning** <br />
$\qquad$ $\qquad$$\qquad$                   **Submitted by: Bitnoori Lee(18hours), Personal No. 19881205-3323, Email bitnoori.lee@gmail.com** <br />

---


General guidelines:
*   All solutions to theoretical and pratical problems must be submitted in this ipynb notebook, and equations wherever required, should be formatted using LaTeX math-mode.
*   All discussion regarding practical problems, along with solutions and plots should be specified in this notebook. All plots/results should be visible such that the notebook do not have to be run. But the code in the notebook should reproduce the plots/results if we choose to do so.
*   Your name, personal number and email address should be specified above.
*   All tables and other additional information should be included in this notebook.
*   Before submitting, make sure that your code can run on another computer. That all plots can show on another computer including all your writing. It is good to check if your code can run here: https://colab.research.google.com.


Self-check 
1. Have you answered all questions to the best of your ability? 
2. Anything else you can easily check? (details, terminology, arguments, commenting for code etc.?) 

Grading will be based on a qualitative assessment of each assignment. It is important to:
*	Present clear arguments
*	Present the results in a pedagogical way
*	Show understanding of the topics (e.g, write a pseudocode) 
*	Give correct solutions
*	Make sure that the code is well commented 

**Again, as mentioned in general guidelines, all code should be written here. And this same ipython notebook file (RLAssignment.ipynb) should be submitted with answers and code written in it. Ipython notebook is mandatory submission. And also submit HTML version of it for easy readibility (goto File/Download as). NO OTHER FORMAT SHALL BE ACCEPTED.** 


# Primer

## Decision Making
The problem of **decision making under uncertainty** (commonly known as **reinforcement learning**) can be broken down into
two parts. First, how do we learn about the world? This involves both the
problem of modeling our initial uncertainty about the world, and that of drawing conclusions from evidence and our initial belief. Secondly, given what we
currently know about the world, how should we decide what to do, taking into
account future events and observations that may change our conclusions?
Typically, this will involve creating long-term plans covering possible future
eventualities. That is, when planning under uncertainty, we also need to take
into account what possible future knowledge could be generated when implementing our plans. Intuitively, executing plans which involve trying out new
things should give more information, but it is hard to tell whether this information will be beneficial. The choice between doing something which is already
known to produce good results and experiment with something new is known
as the **exploration-exploitation dilemma**.

## The exploration-exploitation trade-off

Consider the problem of selecting a restaurant to go to during a vacation.Lets say the
best restaurant you have found so far was **Les Epinards**. The food there is
usually to your taste and satisfactory. However, a well-known recommendations
website suggests that **King’s Arm** is really good! It is tempting to try it out. But
there is a risk involved. It may turn out to be much worse than **Les Epinards**,
in which case you will regret going there. On the other hand, it could also be
much better. What should you do?
It all depends on how much information you have about either restaurant,
and how many more days you’ll stay in town. If this is your last day, then it’s
probably a better idea to go to **Les Epinards**, unless you are expecting **King’s
Arm** to be significantly better. However, if you are going to stay there longer,
trying out **King’s Arm** is a good bet. If you are lucky, you will be getting much
better food for the remaining time, while otherwise you will have missed only
one good meal out of many, making the potential risk quite small.

## Overview
* To make things concrete, we will first focus on decision making under **no** uncertainity, i.e, given we have a world model, we can calculate the exact and optimal actions to take in it. We shall first introduce **Markov Decision Process (MDP)** as the world model. Then we give one algorithm (out of many) to solve it.


* Next, we will work through one type of reinforcement learning algorithm called Q-learning. Q-learning is an algorithm for making decisions under uncertainity, where uncertainity is over the possible world model (here MDP). It will find the optimal policy for the **unknown** MDP, assuming we do infinite exploration.

## Markov Decision Process

Markov Decision Process (MDP) provides a mathematical framework for modeling decision-making. It is a discrete time (distinct points in time) stochastic (randomly determined) process.

MDPs are made up of 4 parts:  
S: Finite set of states (Ex: s<sub>1</sub>, s<sub>2</sub> ... s<sub>N</sub>)  
A: Finite set of actions (Ex: North, South, East, West)  
P<sub>a</sub>(s,s'): Probability that action *a* in state *s* at time *t* will lead to state *s'* at time *t + 1*  
R<sub>a</sub>(s,s'): Immediate reward received after moving from state *s* to state *s'* by action *a*

An agent acts in an MDP at time *t*, by taking certain action *a* in state *s*, going to state *s'*, and getting a reward *r* from the world. It then repeats the process for certain no. of times, either finite or infinite.

We also include a $5^{th}$ part in the description of an MDP called Gamma $\gamma$.  
$\gamma$: The discount factor between 0 (inclusive) and 1 (exclusive). This determines how much credit you want to give to the future. If you think that the future reward is as important as the current reward you would set this to 0.99999. If you don't care about the future rewards you would set this to 0 and you only care about the current reward. For example, if your discount factor is 0.8 and after 5 steps you get a reward of 4 the present value of that reward is $0.8^4 * 5$ or ~2.

An MDP is a collection of states such that each state has a selection of actions associated with them. With each state-action pair comes a reward *r* (can be 0). Define a policy function: $\pi: s \rightarrow a$, which tells which action to take at each state.
  
We now use the famous dynamic programming equation, also known as Bellman Equation, to define optimality in an MDP. The following equation defines what we call the **value function** of state *s* following some fixed policy $\pi$:  

$$V^\pi(s) = \sum_{s'} P_{\pi(s)}(s,s') [R_{\pi(s)}(s,s') + \gamma V^\pi(s')]$$

We call $V^\pi$ as the value of policy $\pi$.  
  
Now, to find the **optimal** policy you will need to find the action that gives the highest reward.  

$$V^*(s) = max_a \sum_{s'} P_a(s,s') [R_a(s,s') + \gamma V^*(s')]$$

A real world example would be an inventory control system. Your states would be the amount of items you have in stock. Your actions would be the amount to order. The discrete time would be the days of the month. The reward would be the profit.  

A major drawback of MDPs is called the "Curse of Dimensionality". This states that the more states/actions you have the more computational difficult it is to solve.   


## Question 1 (2 points)

For the first question of the notebook, we give a quick example of an MDP. We would to see if you can put the definitions above into practice.

**Question a**: Given the following deterministic MDP (you select North, you move North), what is the optimal policy (path with the most points)?
  
*Notes*:  
  * The number in the box is the reward.  
  * Once you hit the end you are done. (Absorbing state)
  * S is the starting point.  
  * F is the ending point.  
  * Use N for North, E for East, S for South, and W for West. Not all actions are available at each state, for example, you can't choose N and W at starting state, as there exists no valid next states in those directions.  
  * Pass the directions as a single string. Ex: ESWN will make a circle.  
  


| | | |
|----------|----------|---------|
|S|1|1|
|1 |0|1|  
|-1|-1|0|  
|0 |0|F|

**Answer a**: 

We can find the optimal policy by hitting the states where you get the point and avoiding states that reduce the point.

The optimal policy is 
In state, 

(0,0): a = E or S 

(1,0): a = E

(2,0): a = S or W

(0,1): a = E

(1,1): a = N, E or W

(2,1): a = N

(0,2): a = N

(1,2): a = N, E or S

(2,2): a = N

(0,3): a = E

(1,3): a = W

(2,3): a = absorbed(finished)

where the optimal path is (0.0) ->(0,1) -> (1,1) -> (1,0) -> (2,0) -> (2,1)-> (2,2)-> (2,3) SENESSS.

Question b,c will attempt to firm up your knowledge of the parts of an MDP. Just remember that for a state denoted by (x,y), state N/E/S/W to that are (x,y-1),(x+1,y),(x,y+1),(x-1,y) respectively. We take (0,0) as the starting state S.





**Question b:** What is the probability of going from state (1,0) to state (2,0) using action E ? ( i.e,  $P_E((1,0),(2,0))$ )

**Answer b:** In deterministic MDP, the agent chooses a unique action in each state. At state (1,0), action E chosen to (2,0), so the probability is 1. 



**Question c:** What is the reward for moving from state (1,0) to state (2,0) ? ( i.e, $R_E((1,0),(2,0))$ )

**Answer c:**
The reward for the action E 
(1,0): a = E, the reward: the value collect once it landed in state (2,0) is 1.  

## Value Iteration


The value function is based on the Bellman Equation for optimal value, which we recall here:  
$$V^*(s) = max_a \sum_{s'} P_a(s,s') [R_a(s,s') + \gamma V^*(s')]$$

The value iteration (VI) is one algorithm that can be used to find the optimal policy ($\pi^*$). Note that for any policy $\pi^*$ to be optimal, it must satisfy the Bellman equation for optimal value function $V^*$. For any candidate $V^*$, it must be such that plugging it in the RHS (right-hand-side) of Bellman equation should give the same $V^*$ again (by the recursive nature of this equation). This property forms the basis of VI algorithm. Essentially, due to certain mathematical results, repeated application of RHS to any intial value function $V^0(s)$ will eventually lead to the value $V^*$ which statifies the Bellman equation. Once converged*, one can extract the optimal actions by simply noting the actions that satisfy the equation.


Note: By 'converge', we mean that the quantity of interest doesn't change anymore by further iterations of the algorithm.

The value iteration algorithm practically procedes as follows:

```
epsilon is a small value, threshold
V_k[s] = 0 for all s
while |V_k[s]-V_k-1[s]| > epsilon for any s
do
    for each state s
    do
        V_k[s] = max_a Σ_s' P_a(s,s')*(R_a(s,s′) + γ*V_k−1[s′])
    end
end

for each state s
do
    π(s)=argmax_a ∑_s′ P_a(s,s')*(R_a(s,s′) + γ*V_k[s′])
end

return π, V_k
```


Example: Below is a 3x3 grid. We are going to walk through a few iterations to firm up your understanding. Lets assume this time that success of taking any action is 0.8. Meaning if we take E from a valid state (x,y), we will go (x+1,y) 0.8 percent of time, but remain in same state the remaining time. We will have a discount factor ($\gamma$) of 0.9. Assume $V^0(s')=0$ for all s'. 

| | | |  
|----------|----------|---------|  
|0|0|0|
|0|10|0|  
|0|0|0|  


**Iteration 1**: It is trivial, V(s) becomes the $max_a \sum_{s'} P_a(s,s') R_a(s,s')$ since $V^0$ was zero for s'.

| | | |  
|----------|----------|---------|  
|0|8|0|
|8|2|8|  
|0|8|0|  
  
**Iteration 2**:  
  
Staring with cell (0,0): We find the expected value of each move:  
Action N: 0  
Action E: 0.8( 0 + 0.9 \* 8) + 0.2(0 + 0.9 \* 0) = 5.76  
Action S: 0.8( 0 + 0.9 \* 8) + 0.2(0 + 0.9 \* 0) = 5.76  
Action W: 0

Hence any action between E and S would have been best at this stage.

Similarly for cell (1,0):

Action S: 0.8( 10 + 0.9 \* 2) + 0.2(0 + 0.9 \* 8) = 10.88 (Action S is the maximizing action)  

Similar calculations for remaining cells give us:

| | | |  
|----------|----------|---------|  
|5.76|10.88|5.76|
|10.88|8.12|10.88|  
|5.76|10.88|5.76|  


## Question 2 (2 points)
Please code the value iteration algorithm just described, and show the optimal value function of the above 3x3 grid problem at convergence (the value function doesn't change anymore).

In [ ]:
import copy
import numpy as np

#functoin array of possible moves for 3x3 grid
def getPossibleAction(state, x, y):

    #array of possible actions 
    possibleAction = []

    if(x > 0): 
        possibleAction.append(('W', x-1,y)) 
    
    if(x < state[0]-1): 
        possibleAction.append(('E', x+1,y))

    if(y > 0): 
        possibleAction.append(('S',x,y-1))

    if(y < state[1]-1): 
        possibleAction.append(('N', x,y+1))
         
    return possibleAction


def getRewards(x, y, lastV, reward, successAction = 0.8, gamma = 1): 
    V = -10000
    Pi = ''
    p = getPossibleAction(reward.shape,x,y)

    for state1,x1,y1 in p:
        # calculate reward (stay, move)
        nextV = successAction * (reward[y1,x1]+gamma*lastV[y1,x1]) + (1-successAction)*(reward[y,x]+gamma*lastV[y,x])

        #Replace reward and save policy if the next one is bigger than before
        if(nextV > V):
            V = nextV
            Pi = state1
    return Pi, V


#Function to find the optimal policy by iterating all state, calling getRewards
def valueIteration(lastV, reward, epsilon=0.1, gamma=0.9):
    
    (row,col) = reward.shape
    V = np.zeros((row, col))
    Pi = np.zeros((row, col), dtype=str)
    #iteration loop
    while True:
        for i in range(row):
            for j in range(col):
                Pi[i,j], V[i,j] = getRewards(j, i, lastV, reward, gamma = 0.9)
        
        if (np.abs(V-lastV)<epsilon).all():
            return Pi, V
        lastV = V.copy()

#Reward matrix
rewards = np.array([(0,0,0),(0,10,0),(0,0,0)])
#Value matrix 
initV = 0*np.ones(rewards.shape)
# call function with initialized parameters and epsilon=0.1
Pi, V = valueIteration(initV, rewards, epsilon=0.1)


# The arrays need to be flipped to show the grid correctly:
print('Initial State:')
print(rewards)
print('Converged State:')
print(V)




Initial State:
[[ 0  0  0]
 [ 0 10  0]
 [ 0  0  0]]
Converged State:
[[44.7917635  51.12689178 44.7917635 ]
 [51.12689178 47.23078789 51.12689178]
 [44.7917635  51.12689178 44.7917635 ]]


"\nprint('Policy:')\nprint(Pi) \n#Reverse the order of elements along axis 0 \nprint('Policy_Ordered:')\nprint(np.flipud(Pi))\n"

## Reinforcement Learning (RL)
Until now, we understood that knowing the MDP, specifically $P_a(s,s')$ and $R_a(s,s')$ allows us to efficiently find the optimal policy using value iteration algorithm, but RL or decision making under uncertainity arises from the question of making optimal decisions without knowing the true world model (MDP in this case).

So far we have defined the value of a state $V^\pi$ (for fixed policy). Let us now define the value of an action, $Q^\pi$:

$$Q^\pi(s,a) = \sum_{s'} P_a(s,s') [R_a(s,s') + \gamma V^\pi(s')]$$

i.e, the value of taking action *a* from state *s* and then following $\pi$ onwards. Similarly, the optimal Q-value equation is:

$$Q^*(s,a) = \sum_{s'} P_a(s,s') [R_a(s,s') + \gamma V^*(s')]$$

## Q-learning

Q-learning algorithm can be used by an agent unaware of its surroundings (unknown MDP). All it can do is take an action *a* at time *t* from state *s* and observe the reward *r* and next state *s'*, and repeat this process again. So how it can learn to act optimally under such uninformative conditions ? Answer is using Q-learning. Without going into its justification, we simply state the main-update rule of this algorithm below:

![alt text](https://chalmersuniversity.box.com/shared/static/5anbos4s9luoayb32jk6w3wy3w4jk3g3.png)

Where we simply maintain Q(s,a) value for each state-action pair in a table. It is proven to converge to the optimal policy of the underlying unknown MDP for a small learning rate $\alpha$ (you have to play around with values ranging from 0.1 to 0.00001)
## OpenAI Gym ($\leq 0.19.0$)

We shall use already available simulators for different environments (world) using the popular OpenAI Gym library. It just implements [differnt types of simulators](https://gym.openai.com/) including ATARI games. Although here we will only focus on simple ones, such as [Chain enviroment](https://gym.openai.com/envs/NChain-v0/).
![alt text](https://chalmersuniversity.box.com/shared/static/6tthbzhpofq9gzlowhr3w8if0xvyxb2b.jpg)

## Question 3 (1 point)
Basically, there are 5 states, and two actions 'a' and 'b'. Each transition (s,a,s') is noted with its corresponding reward. You are to first familiarize with the framework using its [documentation](http://gym.openai.com/docs/), and then implement the "$\epsilon$-greedy Q-learning" algorithm for the Chain enviroment (called 'NChain-v0') using default parameters. Finally print the $Q^*$ table at convergence. Take $\gamma=0.95$. 

Hints:
* You can refer to the Q-learning Jupyter notebook shown in class, uploaded on Canvas.
* Try some decreasing sequences of $\epsilon$ (1/t etc.) with small fixed learning rate $\alpha$.
* Latest Gym version (0.23.1) does not have the Chain environment, you need to install any version $\leq 0.19.0$. You can do so in Google colab by command: " !pip install gym==version ".


In [ ]:
#change version 
!pip install gym==0.19.0
#!pip install gym-toytext


#import gym_toytext
import gym
import numpy as np
import random
import math


# Define environment
env = gym.make("NChain-v0")


In [ ]:
#Define Q_learn function 

def Q_learn(num_episodes, gamma, learning_rate, epsilon): 

# initialize the Q table 5 states and 2 actions 
 Q = np.zeros([5, 2])
 episode_list = [5000,10000,15000,20000]
#Training Q table, code taken from q_learning_intro.ipynb
 for episode in range(num_episodes):
	  state = env.reset()
	  done = False
	  while done == False:
        # First we select an action:
		  if random.uniform(0, 1) < epsilon: # Flip a skewed coin
			  action = env.action_space.sample() # Explore action space
		  else:
			  action = np.argmax(Q[state,:]) # Exploit learned values
        # Then we perform the action and receive the feedback from the environment
		  new_state, reward, done, info = env.step(action)
        # Finally we learn from the experience by updating the Q-value of the selected action
		  prediction_error = reward + (gamma*np.max(Q[new_state,:])) - Q[state, action]
		  Q[state,action] += learning_rate*prediction_error 
		  state = new_state

	 # if episode == 5000 or episode == 10000 or episode == 15000 or 20000:
	 #	 print(Q)
		
	  if episode < 5 or episode > num_episodes - 5: # print Q the first and last few iteration 
	    	print("Episode:", episode)
	    	print(Q)
	    	print()
 #return Q
 

In [ ]:
# Set parameters 
num_episodes = 20000 
gamma = 0.95 #given
learning_rate = 0.1 #0.95 #0.85 alpha // small fixed 
epsilon = 10 ** -1 #go from 1e-1 to 1e-5

while epsilon > 10 ** -5:
#function call trying some decreasing sequences of  𝜖  (1/t etc.) with small fixed learning rate  𝛼.
 #Q = Q_learn(num_episodes, gamma, learning_rate, x/10) #0.6 - .. to make it decreasing order
 print("epsilon:", epsilon)
 Q_learn(num_episodes, gamma, learning_rate, epsilon)
 print()
 epsilon = epsilon/10

epsilon: 0.1
Episode: 0
[[ 9.55716654 20.81333523]
 [18.95652706  6.25674066]
 [20.38866776  5.02230233]
 [ 6.06766717 21.25775231]
 [44.96330961 13.33475044]]

Episode: 1
[[25.06042635 30.25299187]
 [30.0605527  20.42468341]
 [32.4773424  14.63473144]
 [11.44434261 33.93588155]
 [64.77055885 28.84845855]]

Episode: 2
[[31.2700102  33.97476989]
 [34.21859432 22.76905528]
 [35.81392664 21.89868892]
 [28.61675702 40.60251418]
 [66.49829255 34.42891855]]

Episode: 3
[[36.04409393 37.33339441]
 [39.03426401 30.29520045]
 [40.552555   30.71169621]
 [38.91045245 40.87828532]
 [58.45650708 40.95455312]]

Episode: 4
[[41.23191739 45.63317994]
 [50.82485287 33.34175156]
 [55.245068   35.23123869]
 [60.61589845 42.64763848]
 [64.24268938 46.50580694]]

Episode: 19996
[[52.75025177 51.57409491]
 [56.77288556 54.32295368]
 [61.52475173 54.95199613]
 [70.98776743 55.5644305 ]
 [77.58067194 67.45046601]]

Episode: 19997
[[54.52064275 53.32850525]
 [57.60314737 54.79620068]
 [62.15263779 55.42556484]

source: https://gym.openai.com/envs/NChain-v0/ 


source: http://ceit.aut.ac.ir/~shiry/lecture/machine-learning/papers/BRL-2000.pdf


## Question 4 (2 points)

Verify that the optimal $Q^*$ value obtained using Q-learning is same as the optimal value function $V^*$ (for the corresponding optimal action). You would have to first define the MDP corresponding to Chain enviroment.


Hint: 

* "Define the MDP.." means to define "$P_a(s,s')$" and "$R_a(s,s')$" tables for the Chain environment. Its good to know that gym simulator that you use in Q3 takes the correct action with a probability of 0.8 (slip=0.2). This information is useful in defining $P_a(s,s')$ correctly (you can check the nchain.py file by going to the folder specified by 'print(gym.envs.toy_text)' command).

* Once the "p" and "r" tables are defined, you can use your VI implementation from Q2 to compute the "V*(s)". Then the following relation must hold: $V^*(s) = max_a Q^*(s)$ for all s. This proves that the optimal solution can be obtained using Q-learning without knowing the underlying environment model (MDP), unlike the VI algorithm, which needs $P_a,R_a$ information.

In [ ]:
#Define the MDP 
#the correct action with a probability of 0.8 (slip=0.2)
#you can check the nchain.py file by going to the folder specified by 'print(gym.envs.toy_text)' command

print(gym.envs.toy_text)


<module 'gym.envs.toy_text' from '/usr/local/lib/python3.7/dist-packages/gym/envs/toy_text/__init__.py'>


In [ ]:
import copy
import numpy as np

#Defining the MDP
states = [0, 1, 2, 3, 4] #State_space
actions = [0,1] #0 = forward, 1 = backward 
P = 0.8 #the correct action with a probability of 0.8 (slip=0.2)
rewards = [2, 0, 0, 0, 10] #Reward function 
V = [0, 0, 0, 0, 0] #Initial value-function


#Calculate the value-function
for _ in range(20000):
    prevV = copy.deepcopy(V)
    
    s_backward = states[0] #Back to start
    for state in states:
        maxV = 0
        if state <= 3:
            s_forward = states[state+1] #Moving forward
        else:
            s_forward = states[4] #Standin still
        
        for action in actions:
            if action == 0:
                p = 0.8 #the correct action
            else:
                p = 0.2 #slip
            
            #calculates the current expected value for given state and action
            currentV = p*(rewards[s_forward] + gamma*(prevV[s_forward])) + (1-p)*(rewards[s_backward] + gamma*(prevV[s_backward]))

            if (currentV >= maxV):
                curr_pi = action
                maxV = currentV
                    
        #update value matrix with highest expected value at this state      
        V[state] = maxV 


#print("Q:", Q_learn(num_episodes, gamma, learning_rate, 0.01))

def Q_learn_2(gamma, learning_rate, epsilon): 

# initialize the Q table 5 states and 2 actions 
 Q = np.zeros([5, 2])

#Training Q table, code taken from q_learning_intro.ipynb
 for episode in range(20000):
	  state = env.reset()
	  done = False
	  while done == False:
        # First we select an action:
		  if random.uniform(0, 1) < epsilon: # Flip a skewed coin
			  action = env.action_space.sample() # Explore action space
		  else:
			  action = np.argmax(Q[state,:]) # Exploit learned values
        # Then we perform the action and receive the feedback from the environment
		  new_state, reward, done, info = env.step(action)
        # Finally we learn from the experience by updating the Q-value of the selected action
		  prediction_error = reward + (gamma*np.max(Q[new_state,:])) - Q[state, action]
		  Q[state,action] += learning_rate*prediction_error 
		  state = new_state
 return Q

Q = Q_learn_2(gamma, learning_rate, epsilon)
print("Q:", Q)
print()
print("V:", V)

Q: [[56.43698246 46.21150997]
 [60.24972408 45.62109877]
 [64.82972702 51.82878699]
 [69.64060595 41.53297344]
 [74.63997573 58.08063029]]

V: [78.23615999999971, 82.8569599999997, 88.9369599999997, 96.9369599999997, 96.9369599999997]


From the result, the optimal $Q^*$ value obtained using Q-learning is not same as the optimal value function $V^*$. As I can observe in the result of Question 3, the algorithm seem to be sensitive according to hyperparameters. To estimate the reason for obtaining different results from the theory, MDP or initial values are wrong. 

## Question 5 (3 point)

* what was the significance of exploration in RL ? How did you control it in the case Q-learning algorithm ? (1.5 pts)

Exploration is significant in that reinforcement learning agents depend imperatively on exploration to obtain informative data for the learning process and it helps to resolve the lack of information issue which could impede effective learning.

It is necessary that the algorithm explores its environment by taking actions and observing their consequences when the algorithm usually does not have any prior knowledge regarding the task. Moreover, in exploration, the agent improves its knowledge about each action that could lead to the highest reward in opposite to exploitation which chooses the greedy approach. 


In the Q-learning algorithm, Q-learning calculates the rewards for a given chance of exploring (epsilon) in an unknown environment. First of all, we select an action by flipping a skewed coin either explore action space or explore learned values. And then, we perform the action and receive feedback from the environment. And then, we learn from the experience by updating the Q-value of the selected action.


Source: https://ai-ml-analytics.com/reinforcement-learning-exploration-vs-exploitation-tradeoff/

https://analyticsindiamag.com/exploration-reinforcement-learning/#:~:text=A%20classical%20approach%20to%20any,their%20own%20tails%20to%20eternity.


https://en.wikipedia.org/wiki/Multi-armed_bandit#:~:text=In%20probability%20theory%20and%20machine,when%20each%20choice's%20properties%20are





* Briefly discuss the k-armed bandit problem formulation and it's distinguishing feature as a special case of the reinforcement learning problem formulation. (1.5 pts)


The multi-armed bandit problem (K-armed bandit problem) is a problem in which a fixed limited set of resources must be allocated between competing alternative choices in a way that maximizes their expected gain and each choice's properties are only partially known at the time of allocation. and it may become better understood by allocating resources to the choice. This is a classic reinforcement learning problem that exemplifies the exploration-exploitation trade-off dilemma.

source: https://en.wikipedia.org/wiki/Multi-armed_bandit#:~:text=In%20probability%20theory%20and%20machine,when%20each%20choice's%20properties%20are

k-armed bandit problem formulation has distinguishing features as classic reinforcement learning. First, in the k-armed bandit problem, we have k different options to take, each option with a different underlying probability distribution to receive a reward that is unknown at the start. In opposite to supervised learning, we don't know which option is best to get maximized reward, so. we need to find out which option is best based on previous knowledge (exploiting) or at random to find new possibilities (exploring) by trial and error. The optimal decision will probably be somewhere in between the extremes (always explore or always exploit) and will depend on the number of decisions to make. For example, if we use the greedy method that does not use any exploration, which means we always take the same option for all iterations. Instead, if we choose to explore that test-out option randomly then we can have a better chance to find the best option by seeing if there is a better alternative. 


source: https://towardsdatascience.com/reinforcement-learning-multi-arm-bandit-implementation-5399ef67b24b

https://blog.dominodatalab.com/k-armed-bandit-problem#:~:text=In%20its%20basic%20form%2C%20the,chances%20of%20making%20a%20profit.



## Note

* Until now, we have described algorithms for when no. of states and actions are finite. In coming weeks, you will be taught how to extend these methods to continous state enviroments like ATARI games.

# References
Primer/text based on the following references:
* http://www.cse.chalmers.se/~chrdimi/downloads/book.pdf
* https://github.com/olethrosdc/ml-society-science/blob/master/notes.pdf